#!/usr/bin/env bash
# Will print information in regards to a domain and an optional subdomain
# Takes two arguments, domain name followed by subdomain (optional)

function digrun()
{
	res=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | grep -v 'ANSWER SECTION:')
	echo "$res $2" | \
	awk '{print "The subdomain " $6 " is a " $4 " record and points to " $5}'
}

if [ "$2" ]
then
	digrun "$1" "$2"
elif [ "$1" ]
then
	digrun "$1" "www"
	digrun "$1" "lb-01"
	digrun "$1" "web-01"
	digrun "$1" "web-02"
fi
