#!/usr/bin/env bash
# Will transfer file from client to server
ARG_NUM=4

if [ $# == $ARG_NUM ]
then
	scp -o StrictHostKeyChecking=no "$4 $1 '$3@$2':~
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
