#!/usr/bin/env bash
# Will transfer file from client to server
ARG_NUM=4

if [ $# == $ARG_NUM ]
then
	echo "$1 -i $4 -J ~/ '$3@$2' "
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
