#!/usr/bin/env bash
# Will tranfer file from client to a server
# Parameters:
# 1: path to file
# 2: IP of server
# 3: username
# 4: path to private key

if [ $# == 4 ]
then
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi;
