#!/usr/bin/env bash
# Will install Nginx
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
touch /var/www/html/index.html
echo "Hello World" | sudo tee /var/www/html/index.html
sudo service nginx restart
