#!/usr/bin/env bash
# Will install Nginx
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
touch /var/www/html/index.html
echo "Hello World" | sudo tee /var/www/html/index.html
sudo sed -i "41i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
