#!/usr/bin/env bash
# Will set up nginx webserver

# Installs nginx
sudo apt-get update
sudo apt-get -y install nginx

# Enables HTTP
ufw allow 'Nginx HTTP'

# Will create html file containing "Hello World" in plain text
rm -f /var/www/html/index.nginx-debian.html
touch /var/www/html/index.html
echo "Hello World" | sudo tee /var/www/html/index.html

# Nginx Config file
# contains redirect and 404 config
printf %s "\
# Nginx Config Holberton Year 1 Trimester 3
# GPR

server {
	listen 80 default_server;
	listen [::]:80 default_server;

	rewrite ^/redirect_me https://www.youtube.com/watch?v=NHEaYbDWyQE permanent;

	root /var/www/html;

	index index.html index.htm index.nginx-debian.html;

	server_name _;

	error_page 404 /custom_404.html;
	location = /custom_404.html{
		root /usr/share/nginx/html;
		internal;
	}

	location / {
		try_files \$uri \$uri/ =404;
	}
}" > /etc/nginx/sites-available/default

# Configures 404 page
touch /usr/share/nginx/html/custom_404.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

# Restart
service nginx restart
