#!/usr/bin/env bash
# Will install Nginx
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
touch /var/www/html/index.html
echo "Hello World" | sudo tee /var/www/html/index.html
sudo touch /usr/share/nginx/html/custom_404.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "41i\ \n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\
\n\terror_page 404 /custom_404.html;\n\
\tlocation = /custom_404.html{\n\
\t\troot /usr/share/nginx/html;\n\
\t\tinternal;\n\
\t}\n" /etc/nginx/sites-available/default
sudo service nginx restart
