#!/usr/bin/env bash
# Will configure server to assignment specifications
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

mkdir -p /var/www/html
sudo touch /var/www/html/index.html
echo "Hello World" | sudo tee /var/www/html/index.html
sudo touch /usr/share/nginx/html/custom_404.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

sudo printf "\
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	add_header X-Served_By $HOSTNAME;

	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;

	error_page 404 /custom_404.html;
	location = /custom_404.html{
		root /usr/share/nginx/html;
		internal;
	}

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		try_files $uri $uri/ =404;
	}
}" > /etc/nginx/sites-available/default
sudo service nginx restart
