#!/usr/bin/env bash
# Will configure server to assignment specifications
sudo apt-get update
sudo apt-get -y install haproxy

printf "ENABLED=1
" | sudo tee -a /etc/init.d/haproxy
printf "frontend load_balancer
    bind *:80
    mode http
    default_backend webserver

backend webserver
    balance roundrobin
    server 2763-web-01 34.139.37.125:80 check
    server 2763-web-02 23.20.78.65:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service nginx start

