#!/usr/bin/env bash
# Will configure server to assignment specifications
sudo apt-get update
sudo apt-get -y install haproxy

printf "# haproxy config
ENABLED=1
" | sudo tee -a /etc/init.d/haproxy
printf "# haproxy config
frontend haproxynode
        bind *:80
        mode http
        default_backend backendnodes
backend backendnodes
        server web-01 34.139.37.125:80 check
        server web-02 23.20.78.65:80 check
        balance roundrobin
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service nginx start

