#!/usr/bin/env bash
# 10 interations, prints "bad luck" for 4th, "good luck" for 8th, "Best School"

INCRE=0
while [ $INCRE -lt 10 ]
do
	if [ $INCRE -eq 3 ]
	then
		echo "bad luck"
	elif [ $INCRE -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( INCRE++ ))
done
