#!/usr/bin/env bash
# Will display numbers 1 to 20, replacing some with superstitious labels

INCRE=0

until [ $INCRE -eq 21 ]
do
	echo $INCRE
	if [ $INCRE -eq 4 ]
	then 
		echo "bad luck from China"
	elif [ $INCRE -eq 9 ]
	then
		echo "bad luck from Japan"
	elif [ $INCRE -eq 17 ]
	then
		echo "bad luck from Italy"
	fi
	((INCRE++))
done
