#!/usr/bin/env bash
# Will display numbers 1 to 20, replacing some with superstitious labels

INCRE=1

until [ $INCRE -eq 21 ]
do
	echo $INCRE
	case $INCRE in
	4) 
			echo "bad luck from China"
		;;
	9)
			echo "bad luck from Japan"
		;;
	17)
			echo "bad luck from Italy"
		;;
	esac
	((INCRE++))
done
